### PR TITLE
Fixes #989 WARN: require cycle

### LINKED ISSUE #989: WARN: require cycle
I'm receiving the following WARN:

```
[Mon Jul 06 2020 11:23:53.136]  WARN     Require cycle: node_modules/react-native-track-player/lib/trackPlayer.js -> node_modules/react-native-track-player/lib/ProgressComponent.js -> node_modules/react-native-track-player/lib/trackPlayer.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```
It's not a bug but it's not cool to have it. I solved it already and it works for me, submitting a pull request shortly.

### PR DESCRIPTION
**Pull request by Tubaleviao**
Fixes issue #989. I have tested in another environment and the basic functionalities worked fine.

### CODE REVIEW

**Comment by nickmcmillan** [comment]
Any chance of this being merged soon? `1.2.3` is the current latest version on npm, and it still has the issue (as identified in https://github.com/react-native-kit/react-native-track-player/issues/1057)

**Comment by mohamad-1994** [comment]
I have same problem for service.js , app stop working if I use event listeners in service.js

**Review by cenksari — APPROVED** [review]

**Comment by ankitjaiswal1994** [comment]
Any update here ?

**Comment by justinhandley** [comment]
I'd also love to see this merged in.

**Comment by curiousdustin** [comment]
Fix released in [1.2.4](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.2.4)

**Pull request closed without merging**
