### PR TITLE
[ios] Handle interruption & support remote-duck

### PR DESCRIPTION
**Pull request by minhtc**

### CODE REVIEW

**Comment by Guichaguri** [comment]
Why not use the same parameters sent by Android? It seems like it can be mapped in the following way:

| iOS State | TrackPlayer parameter |
| ---------- | ------------------------ |
| `began` | `{paused: true, permanent: false, ducking: false}` |
| `shouldResume` | `{paused: false, permanent: false, ducking: false}` |
| `shouldNotResume` | `{paused: false, permanent: true, ducking: false}` |

An implementation like this one would work on both platforms:
```js
(event) => {
    if (event.permanent) {
        TrackPlayer.stop();
    } else if (event.paused) {
        TrackPlayer.pause();
    } else if (event.ducking) {
        TrackPlayer.setVolume(0.5);
    } else {
        TrackPlayer.setVolume(1);
        TrackPlayer.play();
    }
}
```

**Comment by minhtc** [comment]
> Why not use the same parameters sent by Android? It seems like it can be mapped in the following way:
> 
> iOS State	TrackPlayer parameter
> `began`	`{paused: true, permanent: false, ducking: false}`
> `shouldResume`	`{paused: false, permanent: false, ducking: false}`
> `shouldNotResume`	`{paused: false, permanent: true, ducking: false}`
> An implementation like this one would work on both platforms:
> 
> ```js
> (event) => {
>     if (event.permanent) {
>         TrackPlayer.stop();
>     } else if (event.paused) {
>         TrackPlayer.pause();
>     } else if (event.ducking) {
>         TrackPlayer.setVolume(0.5);
>     } else {
>         TrackPlayer.setVolume(1);
>         TrackPlayer.play();
>     }
> }
> ```

I was think about mapping same parameters, but I decided to keep separate from android, because it's very different handler on each platform. In iOS we can't play, pause, or setVolume during call. Bellow is my js code to handle audio interruptions:

```js
      if (Platform.OS === 'ios' && data === 'shouldResume') {
        Player.play();
      } else if (Platform.OS === 'android') {
        if (data.paused) {
          const currentState = await TrackPlayer.getState();
          wasPlaying = currentState === TrackPlayer.STATE_PLAYING;
          Player.pause();
        } else if (data.ducking) {
          Player.pause();
        } else if (wasPlaying) {
          Player.play();
          wasPlaying = false;
        }
      }
```

**Comment by anderslemke** [comment]
Duplicate of #530?

**Comment by dcvz** [comment]
This has been merged as part of #530

**Pull request closed without merging**
