### PR TITLE
[iOS] Send remote events when interruption handling

### PR DESCRIPTION
**Pull request by anderslemke**
To allow the application doing whatever needs to be done when pausing.

### CODE REVIEW

**Comment by Guichaguri** [comment]
Correct if I'm wrong, but shouldn't it trigger the [`remote-duck`](https://react-native-kit.github.io/react-native-track-player/documentation/#remote-duck) event?

**Comment by anderslemke** [comment]
I think you're right, @Guichaguri .

I'm using `remote-duck` now.

**Comment by anderslemke** [comment]
This branch is running in production on our app now.

We might need to add some documentation, as your app needs to keep track of it's state when `remote-duck` is sent, to know if it should start playing or not when the ducking stops.

iOS will send event with `. shouldResume` regardless of if your app was playing or not when the interruption started.

**Comment by vdesdoigts** [comment]
Any update for this? I need it :)

**Comment by dcvz** [comment]
This looks great @anderslemke ! thank you for this 🙏

**Pull request merged**
