### PR TITLE
Resolve problem with android app compilation

### PR DESCRIPTION
**Pull request by oleksii-sauliak**
My project build failed on Task :react-native-track-player:compileDebugJavaWithJavac

```
G:\projects\centenis-tours-mobile-rn\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:20: error: package android.support.v4.media.app.NotificationCompat does not exist
import android.support.v4.media.app.NotificationCompat.MediaStyle;
                                                      ^
G:\projects\centenis-tours-mobile-rn\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:42: error: cannot find symbol
    private MediaStyle style;
            ^
  symbol:   class MediaStyle
  location: class MediaNotification
G:\projects\centenis-tours-mobile-rn\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:58: error: constructor Builder in class Builder cannot be applied to given types;
        this.nb = new Builder(context, "trackplayer");
                  ^
  required: Context
  found: Context,String
  reason: actual and formal argument lists differ in length
G:\projects\centenis-tours-mobile-rn\node_modules\react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:59: error: cannot find symbol
        this.style = new MediaStyle().setMediaSession(session.getSessionToken());
                         ^
  symbol:   class MediaStyle
  location: class MediaNotification
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':react-native-track-player:compileDebugJavaWithJavac'.
Compilation failed; see the compiler error output for details.

```

As I can see there is a problem with import NotificationCompat.MediaStyle.
`import android.support.v4.media.app.NotificationCompat.MediaStyle;`
`react-native-track-player\android\src\main\java\guichaguri\trackplayer\metadata\components\MediaNotification.java:20`
I can fix this issue by adding `compile 'com.android.support:support-v4:27.0.0'` to dependencies in build.gradle

### CODE REVIEW

**Comment by dcvz** [comment]
Thank you for this! This will be resolved with https://github.com/react-native-kit/react-native-track-player/pull/165

**Comment by maendamedia** [comment]
Is this already fixed as i get the same error on the latest fresh install.

`error: package android.support.v4.media.session does not exist`

**Comment by dcvz** [comment]
in that branch I mentioned above?

**Comment by maendamedia** [comment]
Yes i installed fresh copy. Should i add a special branche?

Hmm i see "react-native-track-player": "^0.2.5",

That looks not correct?

**Comment by maendamedia** [comment]
Still same error what ever i try.


```
../node_modules/react-native-track-player/android/src/main/java/guichaguri/trackplayer/TrackModule.java |  
-- | --
error: package android.support.v4.media does not exist |  
error: package android.support.v4.media.session does not exist |  
error: cannot find symbol variable PlaybackStateCompat |  
error: cannot find symbol variable PlaybackStateCompat |  
error: cannot find symbol variable PlaybackStateCompat |  
error: cannot find symbol variable PlaybackStateCompat |  
error: cannot find symbol variable PlaybackStateCompat |  
error: cannot find symbol variable PlaybackStateCompat |  


```

**Comment by dcvz** [comment]
That's not the correct version. We've now published `v1.0.0` to npm. You can see the changelog [here](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.0.0).

**Pull request closed without merging**
