### PR TITLE
Added custom headers to the track

### LINKED ISSUE #304: send headers for audio
i wanna send header for Authorization of file is possible ??
like this ::

`await TrackPlayer.add({
        id: 'trackId',
        url:
                {
                    uri:'https://abc.com/download/67',
                    method: 'Get',
                    headers: {
                        'Authorization': 'Bearer ' + this.props.user.access_token,
                        'Content-Type': 'application/json',
                    }
                },
        title: 'Track Title',
        artist: 'Track Artist',
        artwork: require('track.png')
    });`

### PR DESCRIPTION
**Pull request by Guichaguri**
This PR adds the support for defining custom HTTP headers to tracks. Closes #304.

### CODE REVIEW

**Comment by Guichaguri** [comment]
@dcvz Are custom http headers doable (or at least not too complex to do), in iOS?

**Comment by mkuczera** [comment]
@Guichaguri we implemented custom headers support on a private fork at our company. It´s actually outdated and based on 1.0.2, but if there is no one currently working on it, i can make the iOS solution.

**Comment by Guichaguri** [comment]
@mkuczera That would be awesome! 🤩
You can fork the `feat/http-headers` branch and create a PR like you normally would, then I can merge your PR into this one.

**Comment by dcvz** [comment]
@Guichaguri this is done now in 418934123a721f25cee9d2d829907d202d9057e6, should we merge Android support to?

**Comment by Guichaguri** [comment]
Yep, thank you!

**Comment by ShivamJoker** [comment]
@Guichaguri if we pass headers will it be sent on every HLS request as well?
The manifest which is coming from the first response?

**Pull request merged**
