### PR TITLE
Modernize Library Bundling

### PR DESCRIPTION
**Pull request by dcvz**
Rewrites library in typescript with proper `lib` and `types` output also adds `eslint` support :)

**WARNING**
With we deprecate the `ProgressComponent` which I think is ok as most people are on hooks now and we have an implementation for progress with hooks.

**BREAKING**
Now only direct methods on the player are exported as default on `TrackPlayer`. `State`, `Capability`, `PitchAlgorithm`, `TrackType` and `Event` are now exported as enums.

To use them you'll have to `import { State } from 'react-native-track-player'`

Same applies to hooks `import { useTrackPlayerProgress }  from 'react-native-track-player'`

I've updated the example accordingly.

### CODE REVIEW

**Comment by dcvz** [comment]
I'll run some tests on existing project and then merge this @Guichaguri

**Comment by dcvz** [comment]
With this we'd deprecate the `ProgressComponent` which I think is ok as most people are on hooks now. We can make this part of the `2.0.0` release.

**Comment by dcvz** [comment]
BREAKING: `State`, `Capability`, `PitchAlgorithm`, `TrackType` and `Event` are now exported as enums and not part of the `default export`.

To use them you'll have to `import { State } from 'react-native-track-player`

I've updated the example accordingly.

**Comment by Guichaguri** [comment]
Nice! That should be going into 2.0.0, right?

**Comment by dcvz** [comment]
Yup @Guichaguri I'll merge it in now, but should be part of the 2.0.0 release

**Comment by dcvz** [comment]
@Guichaguri Yes! I've merged this now into a `v2` branch where we can collect work

**Pull request merged**
