### PR TITLE
Feat/http headers

### PR DESCRIPTION
**Pull request by mkuczera**

### CODE REVIEW

**Comment by dcvz** [comment]
It's a bit hard to properly review this. @Guichaguri could you maybe rebase the base branch? 

As this is also including a lot of additions from the main branch,.

**Comment by Guichaguri** [comment]
@dcvz The only commit that have the actual changes is the https://github.com/react-native-kit/react-native-track-player/pull/584/commits/0db06bdaddbb60466e7116ac1cd1c76cba0ebd7d. Other than that, the rest is a dev branch merge.

**Comment by mkuczera** [comment]
@dcvz @Guichaguri any progress?

**Comment by Guichaguri** [comment]
Please, could you create a new PR with only the changes you made, without merging the dev branch? That would be a lot easier to review and merge.

**Comment by mkuczera** [comment]
Extracted in #621

**Pull request closed without merging**
