### PR TITLE
Fix android 5 and android 8 related issues

### PR DESCRIPTION
**Pull request by seb0zz**
This PR fixes / or finds a workaround for different cases in which Android 5 and Android 8 users are facing errors.

### CODE REVIEW

**Comment by Buthrakaur** [comment]
@seb0zz this should fix https://github.com/react-native-kit/react-native-track-player/issues/226 , right?

**Comment by seb0zz** [comment]
@Buthrakaur yes it should :v: at least for us it does fix it.

**Comment by dcvz** [comment]
Is this still necessary following the release of 1.0.0?

**Comment by Guichaguri** [comment]
I don't think it is, I'll be closing it for inactivity. Feel free to reopen it if there are still anything that can be reused from this PR.

**Pull request closed without merging**
