### PR TITLE
 Add Constants and export Handler

### PR DESCRIPTION
**Pull request by rtmalone**
In reference to #325

### CODE REVIEW

**Comment by ataravati** [comment]
@dcvz This issue has been resolved in the new release (v1.1.0), but now, I have to do `TrackPlayer.RNTrackPlayer.setupPlayer()` instead of `TrackPlayer.setupPlayer()`. Also, `addEventHandler` method does not exist.

**Comment by ataravati** [comment]
@dcvz Just to clarify, `TrackPlayer.setupPlayer()` gives me a syntax error, but it works. `TrackPlayer.RNTrackPlayer.setupPlayer()`, on the other hand, doesn't give me a syntax error, but it gives me a runtime error.

**Comment by Guichaguri** [comment]
@ataravati can you try 94d64db7904b1aae328351f9cab2e59067099599?

**Comment by dcvz** [comment]
Test and confirmed to be working with https://github.com/react-native-kit/react-native-track-player/commit/94d64db7904b1aae328351f9cab2e59067099599, I'll go ahead and close this issue now :)

**Comment by ataravati** [comment]
@Guichaguri I upgraded the package to the latest version (v1.1.1) and the issue was resolved. Thanks!

**Pull request merged**
