### PR TITLE
[CHORE] - set proper Podspec setup

### PR DESCRIPTION
**Pull request by mkuczera**
While using with RN 0.60.0 i experiences problems with the autolinking and the podspec settings.

### CODE REVIEW

**Comment by mhabegger** [comment]
Try upgrading to 2.0.0-rc10. With rc4 the project tries to build the examples from react-native-track-player which fail.

```
npm i react-native-track-player@2.0.0-rc10
```

**Comment by dcvz** [comment]
This is already done in the `v2` branch which we're working on releasing soon @mkuczera. As @mhabegger mentioned, you can try using `@next`.

**Comment by mkuczera** [comment]
Hi,
the source files are now correct. But actually the podspec is missing the swift_version added in this PR:
https://github.com/react-native-kit/react-native-track-player/pull/657/files#15

"`react-native-track-player` does not specify a Swift version and none of the targets (`Jukebox_Mobile`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod."

**Comment by Bang9** [comment]
@dcvz @mhabegger 
How about reopen it and merge?
please read this PR(#690)

**Pull request closed without merging**
