### PR TITLE
#V2 Fix podspec import

### PR DESCRIPTION
**Pull request by benjipott**
Remove sub module and use podspec instead and link SwiftAudio library

### CODE REVIEW

**Comment by alfonsodev** [comment]
Hi, can you add
```
  s.swift_version = '5.0'
```
to the podspec, it is causing errorrs
```
[!] Unable to determine Swift version for the following pods:

- `react-native-track-player` does not specify a Swift version and none of the targets (`avid`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by benjipott** [comment]
Hi @alfonsodev done

**Comment by alfonsodev** [comment]
Hi @benjipott sorry for my comment it was too precipitated, I'm actually not sure about that anymore.
Currently I'm testing with your branch and `pod install` works without any warning about swift version 👍

But the XCode build fails with the following errors 

image

do you have any idea how to fix it ?

**Comment by alfonsodev** [comment]
I can confirm after running `react-native link react-native-swift` your branch builds correctly

**Comment by benjipott** [comment]
@Guichaguri any idea when this pr can be merged in v2 ?

**Comment by alfonsodev** [comment]
@benjipott 
does `react-native run-ios --configuration Release` work for you ?
I'm getting 
```
fatal error: module map file '/Users/alfonso/Library/Developer/Xcode/DerivedData/avid-dzwhofcxokyzvbgrircdbpntyevu/Build/Products/Debug-iphonesimulator/SwiftAudio/SwiftAudio.modulemap' not found
```
error

**Comment by benjipott** [comment]
@alfonsodev no problems on my side

**Comment by benjipott** [comment]
@Guichaguri any chances to merge this or upgrade npm ?

**Comment by curiousdustin** [comment]
@benjipott Thanks for your work on this. I referenced it heavily in https://github.com/react-native-kit/react-native-track-player/pull/904. Just wanted to get this into `dev` first. Changes are being applied to v2 as well.

**Pull request closed without merging**
