### PR TITLE
Change media buttons to directly affect the player

### PR DESCRIPTION
**Pull request by Guichaguri**
As discussed in #94, this PR removes the media button events and link them directly to the player.

### CODE REVIEW

**Comment by ferrannp** [comment]
@Guichaguri do you plan to merge this? 😃

**Comment by Guichaguri** [comment]
No, we didn't decided what we will be doing yet. If you want, you can join the discussion in #94.

**Comment by dcvz** [comment]
@Guichaguri multiple users have requested that we keep the capability to forward remote events to JS. However as previously stated: I think there will be a huge benefit, especially on Android, to handle this directly from the player. So let's handle it from the player and allow the option for users to still get notified of changes.

I've updated the iOS side to always handle natively. I've also added a new key `forwardRemoteEventsToJS` that users can provide in the `updateOptions`. If that key is `true` then I'll also forward the event to JS.

**Comment by dcvz** [comment]
I believe this was solved with release v1.0.0 so I'll close this now.

**Pull request closed without merging**
