### PR TITLE
Types for hooks

### PR DESCRIPTION
**Pull request by alangumer**

### CODE REVIEW

**Comment by Andruschenko** [comment]
Could this PR please be reviewed and merged? It looks good to me.

**Comment by oshtman** [comment]
Isn't the handler for `useTrackPlayerEvents` missing the event payload as argument?
This line: https://github.com/react-native-kit/react-native-track-player/pull/680/commits/0a65fb3d07eb3d6e3a88577d2dfe13ee2f222a60#diff-b52768974e6bc0faccb7d4b75b162c99R206

**Comment by curiousdustin** [comment]
Added. https://github.com/react-native-kit/react-native-track-player/commit/908b52eeac1e4cbcc3af8a9e23d8a53f7dde4e39

**Comment by curiousdustin** [comment]
Released in [1.2.4](https://github.com/react-native-kit/react-native-track-player/releases/tag/v1.2.4)

**Pull request merged**
