### PR TITLE
react-native-track-player: Add support for CocoaPods

### PR DESCRIPTION
**Pull request by Meninblack007**
Added support for CocoaPods. Works just fine.
Feel free to update Podspec.

### CODE REVIEW

**Comment by Meninblack007** [comment]
@dcvz any update on this?

**Comment by dcvz** [comment]
Hey @Meninblack007 I've had a busy week, but I'll take look at it later today 💃

**Comment by sukhdeep540** [comment]
Any update for the cocoa pods support?

**Comment by Meninblack007** [comment]
@dcvz looks like you are busy :P

**Pull request merged**
