### PR TITLE
[ios] Make setupPlayer idempotent

### PR DESCRIPTION
**Pull request by anderslemke**

### CODE REVIEW

**Comment by anderslemke** [comment]
OK. This doesn't seem to work.

So your best option is probably to only call `setupPlayer` once from your JS.

Either way, if you call more than once, you get multiple event listeners.

**Comment by dcvz** [comment]
Why not just add a flag that makes sure it isn't run again?

**Comment by curiousdustin** [comment]
@anderslemke , sounds like this should be closed?

**Comment by puckey** [comment]
@anderslemke I am going to close this pull request, since you stated it does not work. If you want to have it reopened, please let us know.

**Pull request closed without merging**
