### PR TITLE
[ios] Add ability to jump forward by some interval

### PR DESCRIPTION
**Pull request by dcvz**
Adds new capabilities:
- `CAPABILITY_JUMP_FORWARD`
- `CAPABILITY_JUMP_BACKWARD`

These will allow the control center to display an appropriate jump forward / backward button with the specified interval time. You can specify this interval time by passing in a "jumpInterval" parameter to `updateOptions({})`.

screen shot 2017-11-21 at 16 28 24

Example:
```js
await TrackPlayer.updateOptions({
    jumpInterval: 15,
    capabilities: [
        TrackPlayer.CAPABILITY_JUMP_FORWARD,
        TrackPlayer.CAPABILITY_JUMP_BACKWARD,
    ]
})
```

It will then fire an event `remote-jump-forward/backward` with payload: `{interval: XX}`.

### CODE REVIEW

**Comment by dcvz** [comment]
@anderslemke would you like to test out this feature? 🚀

**Comment by Guichaguri** [comment]
Android also supports jump forward/backward, I will definitely implement the same capabilities and option for that.
I can also add a notification button, but most music apps on Android don't have it. Let me know if you think the notification button is also a good idea.

**Comment by dcvz** [comment]
@Guichaguri I think it might be a good idea to also include it in this branch.. that way new features are always available for both platforms at the same time.

**Comment by Guichaguri** [comment]
@dcvz The Android part is done, feel free to merge it

**Comment by egorkhmelev** [comment]
Would be great to add notification buttons as well for Android. I can do a PR if needed.

**Comment by Guichaguri** [comment]
@egorkhmelev I thought about it, but as almost no music apps do it on Android, it just seems like a bad UX

**Comment by egorkhmelev** [comment]
@guichaguri what about podcasts app? Seems like essential feature to be able to jump back. Would be great to provide such option. Otherwise people will just fork and reimplement that themselves if needed (as I did) coz its a design requirement and I cannot see how rewind button can be a bad UX. Besides iOS has such option out of the box implemented on system level.

**Comment by dcvz** [comment]
@egorkhmelev do you have a podcast app on your Android? Can you show us what that looks like?

**Comment by egorkhmelev** [comment]
Sure. This is Pocket Casts — one of the best podcasts app out there:
screenshot_20171231-092437

The following is what I was able to get from this lib so far:
screenshot_20171231-092535

**Comment by Guichaguri** [comment]
@egorkhmelev Here you go, I made the notification buttons configurable, so podcast apps can optionally have it, and music apps can leave the notification without them.

**Comment by dcvz** [comment]
looks great @Guichaguri! Can I merge this now?

**Comment by Guichaguri** [comment]
Yep :)

**Comment by egorkhmelev** [comment]
You guys are amazing 👍

**Comment by sagargheewala** [comment]
Hey,

Can you please share a implemented code.

I have put below code in  **updateOptions()**  but not display forward and backward icon.

   jumpInterval: 15,
    capabilities: [
        TrackPlayer.CAPABILITY_JUMP_FORWARD,
        TrackPlayer.CAPABILITY_JUMP_BACKWARD,
    ]

Please help me!

**Comment by Guichaguri** [comment]
@sagargheewala Are you using the dev branch?

**Comment by sagargheewala** [comment]
@Guichaguri Yes, this is done from my mistake.

Another thing
How to enable seek-bar?

Thanks for replay.

**Comment by Pczek** [comment]
Great job!
Documentation is missing #284 though.

**Pull request merged**
